title: engineering.art.science
email: zjor_DOT_se_AT_gmail
description: > 
  Notes on my crazy ideas and half-finished projects
baseurl: "" 
url: "https://zjor.github.io" 
twitter_username: zjor
github_username:  zjor

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

disqus:
  shortname: zjor

excerpt_separator: <!--more-->

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
